SELECT  TOP 1 EmployeeFirstName, EmployeeLastName,COUNT(DISTINCT(ORDER_LINE_T.ProductID)) as 'DISTINCT SALES'
From EMPLOYEE_T
	JOIN CUSTOMER_T
		ON EMPLOYEE_T.EmployeeID=CUSTOMER_T.SalesRepID
	JOIN ORDER_T
		ON ORDER_T.CustomerID = CUSTOMER_T.CustomerID
	JOIN ORDER_LINE_T
		ON ORDER_LINE_T.OrderID = ORDER_T.OrderID
	JOIN PRODUCT_T
		ON PRODUCT_T.ProductID = ORDER_LINE_T.ProductID
GROUP BY EmployeeFirstName, EmployeeLastName
