SELECT PRODUCT_T.ProductDescription,PRODUCT_SUPPLIER_T.ProductCost
FROM PRODUCT_T
	JOIN FABRICATED_T
		ON FABRICATED_T.PartID = PRODUCT_T.ProductID
	JOIN PRODUCT_SUPPLIER_T
		ON PRODUCT_SUPPLIER_T.ProductID = PRODUCT_T.ProductID
	JOIN FABRICATED_T

WHERE PRODUCT_T.ProductDescription = 'Hack Saw'
and PRODUCT_T.ProductID = FABRICATED_T.PartID
