SELECT Product_T.ProductDescription, PRODUCT_SUPPLIER_T.ProductCost
FROM FABRICATED_T
	JOIN PRODUCT_T
		ON PRODUCT_T.ProductID = FABRICATED_T.PartID
		AND  FABRICATED_T.ProductID=(SELECT 
			PRODUCT_T.ProductID FROM PRODUCT_T
			WHERE PRODUCT_T.ProductDescription='Hack Saw'
		)
	JOIN PRODUCT_SUPPLIER_T
		ON PRODUCT_SUPPLIER_T.ProductID = PRODUCT_T.ProductID
		